# Default values for nodejs-welcome.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

secretName: registry-secret
image:
  repository: quay.io/mkzaw/lfs274
  tag: v1

service:
  name: node-app-svc
  type: ClusterIP
  port: 8080

ingress:
  enabled: false
  className: "nginx"
  hosts: chart-example.local